version: '3.8'

services:
  postgresql_db_auth:
    image: postgres:latest
    container_name: postgresql_db_auth
    ports:
      - "5434:5432" 
    volumes:
      - postgres_db_data_auth:/var/lib/postgresql/data
    env_file:
      - .env  
    environment:
      - POSTGRES_USER=${POSTGRES_USER_AUTH} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_AUTH}  
      - POSTGRES_DB=${POSTGRES_DB_AUTH} 

volumes:
  postgres_db_data_auth:
