name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
        
      - name: Install dependencies for api-gateway-auth
        run: |
          cd api-gateway-auth
          npm ci
          
      - name: Install dependencies for api-url-shortener
        run: |
          cd api-url-shortener
          npm ci
          
      - name: Run Lint for api-gateway-auth
        run: |
          cd api-gateway-auth
          npm run lint
          
      - name: Run Lint for api-url-shortener
        run: |
          cd api-url-shortener
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
        
      - name: Install dependencies for api-gateway-auth
        run: |
          cd api-gateway-auth
          npm ci
          
      - name: Install dependencies for api-url-shortener
        run: |
          cd api-url-shortener
          npm ci
          
      - name: Run Jest tests with coverage for api-gateway-auth
        run: |
          cd api-gateway-auth
          npm run test
          
      - name: Run Jest tests with coverage for api-url-shortener
        run: |
          cd api-url-shortener
          npm run test
